stages:
  - build
  - test
  - QualityGate

job1:
  stage: build
  tags:
    - LMJ-CI-1
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/lsh-cluster-oam-kubernetes-runtime ./main.go

job2:
  stage: test
  tags:
    - LMJ-CI-1
  script:
    - "/usr/local/scanner/sonar-scanner-4.3.0.2102-linux/bin/sonar-scanner -X \
                                      -Dsonar.sonar.login=admin \
                                      -Dsonar.sonar.password=admin \
                                      -Dsonar.language=go \
                                      -Dsonar.projectKey=${CI_PROJECT_NAME} \
                                      -Dsonar.projectName=${CI_PROJECT_NAME} \
                                      -Dsonar.projectVersion=1.0 \
                                      -Dsonar.ws.timeout=30 \
                                      -Dsonar.projectDescription=${CI_PROJECT_TITLE} \
                                      -Dsonar.links.homepage=${CI_PROJECT_URL} \
                                      -Dsonar.sources=${CI_PROJECT_DIR} \
                                      -Dsonar.sourceEncoding=UTF-8 \
                                      -Dsonar.java.binaries=${CI_PROJECT_DIR} \
                                      -Dsonar.branch.name=${CI_COMMIT_REF_NAME} "

job3:
  stage: QualityGate
  tags:
    - LMJ-CI-1
  script:
    - echo ${CI_PROJECT_NAME}
    - AA=`curl -X GET "http://8.16.0.97:9000/api/measures/search?projectKeys=${CI_PROJECT_NAME}&metricKeys=alert_status" | sed 's/":"/\\n/g' | sed 's/","/\\n/g' | awk 'NR==4 {print}'`
    - echo $AA
    - if [ ${AA} == OK ]; then
    -     echo "sonarqube通过"
    - else
    -     echo "sonarqube失败 http://8.16.0.97:9000"
    -     exit 1
    - fi
