apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: compent-canary-v2
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: compent-canary-v2
    spec:
      pointToGrayName: compent-canary-v1
      serviceMesh: true
      containers:
        - name: canary
          image: xishengcai/canary
          ports:
            - containerPort: 80
              name: canary
          env:
            - name: VERSION
              value: v2
