apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: compent-canary
spec:
  components:
    - componentName: compent-canary-v1
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: CanaryTrait
            metadata:
              name:  compent-canary-v1
              namespace: default
            spec:
              type: traffic
              proportion: 20
    - componentName: compent-canary-v2
