apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: oam-sts-config
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: oam-sts-config
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: wordpress
          config:
            - path: /opt/xxx.log
              value: dddddaaaaaa
