apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: oam-sts-config
spec:
  components:
    - componentName: oam-sts-config
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: VolumeTrait
            metadata:
              name: oam-volume-trait
            spec:
              volumeList:
              - containerIndex: 0
                paths:
                - size: 20Gi
                  path: /var/log/test
                  storageClassName: alicloud-disk-efficiency
                  name: path-1

