apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: sts-example
spec:
  workload:
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mongo-rs
      namespace: default
    spec:
      podManagementPolicy: OrderedReady
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: mongo-rs
      serviceName: mongo-rs-svc
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "2022-04-11T23:03:43-04:00"
          creationTimestamp: null
          labels:
            app: mongo-rs
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - mongo-rs
                  topologyKey: kubernetes.io/hostname
          containers:
            - command:
                - sh
                - -c
                - numactl --interleave=all mongod -f /etc/conf.d/mongodb --replSet rs
              env:
                - name: MONGO_INITDB_DATABASE
                  value: admin
                - name: MONGO_INITDB_ROOT_USERNAME
                  value: root
                - name: MONGO_INITDB_ROOT_PASSWORD
                  value: "123456"
              image: registry.cn-hangzhou.aliyuncs.com/launcher/mongo:4.2.1
              imagePullPolicy: IfNotPresent
              name: mongod
              ports:
                - containerPort: 27017
                  protocol: TCP
              resources:
                limits:
                  cpu: "2"
                  memory: 2G
                requests:
                  cpu: 500m
                  memory: 500m
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/lib/mongodb
                  name: mongodb-data
                - mountPath: /etc/conf.d
                  name: mongo-config
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 10
          volumes:
            - hostPath:
                path: /usr/local/mongodb1
                type: ""
              name: mongodb-data
            - configMap:
                defaultMode: 420
                name: mongodb-rs-config
              name: mongo-config