apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dependency-clusterrole
  labels:
    rbac.oam.dev/aggregate-to-controller: "true"
rules:
  - apiGroups:
      - example.com
    resources:
      - 'foo'
    verbs:
      - '*'
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: source
spec:
  workload:
    apiVersion: example.com/v1
    kind: Foo
    metadata:
      name: source
    spec:
      key: test-value
    status: # comment this part to mimic dependency wait time.
      state: pending
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: sink
spec:
  workload:
    apiVersion: example.com/v1
    kind: Foo
    metadata:
      name: sink
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: source
      dataOutputs:
        - name: example-key
          fieldPath: "spec.key"
          conditions:
            - op: eq
              value: running
              fieldPath: "status.state"
    - componentName: sink
      dataInputs:
        - valueFrom:
            dataOutputName: example-key
          toFieldPaths:
            - "spec.key"
