apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: redis
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis

