apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: oam-component-sts
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: oam-component-sts
    spec:
      type: statefulset
      forceUpdateTimestamp: xxxx1
      containers:
        - name: nginx1
          image: nginx
          ports:
            - containerPort: 80
              name: nginx
        - name: sockjs
          image: xishengcai/sockjs
          ports:
            - containerPort: 8080
              name: sockjs
