apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-sts
spec:
  components:
    - componentName: oam-component-sts
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: VolumeTrait
            metadata:
              name: grafana
            spec:
              volumeList:
                - containerIndex: 0
                  isInitContainer: false
                  paths:
                    - path: /var/log/test
                      name: html-1
                      storageClass: local-path
