apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: component-dep
  namespace: default
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.6.1-apache
          ports:
            - containerPort: 80
              name: wordpress
            - containerPort: 81
              name: test
          env:
            - name: TEST_ENV
              value: test
          resources:
            cpu:
              required: "60m"
              limits: "100m"
            memory:
              required: "60Mi"
              limits: "100Mi"
  parameters:
    - name: instance-name
      required: true
      fieldPaths:
        - metadata.name
    - name: image
      fieldPaths:
        - spec.containers[0].image
